apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    name: hello-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30880
  selector:
    name: hello-pod