apiVersion: v1
kind: Service
metadata:
  name: timestamp-service
  labels:
    name: timestamp-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: timestamp-pod